function patient = TCoMX_COMPUTE_METRICS(tomoplan, METRICS_LIST)
    
functions = {@TCoMX_LOTstats, ...
             @TCoMX_nOC, ...
             @TCoMX_EPSTV, ...
             @TCoMX_ELOTV, ...
             @TCoMX_MI, ...
             @TCoMX_LNS, ...
             @TCoMX_CLS, ...
             @TCoMX_SI, ...
             @TCoMX_MSA};

patient = [];

for funcidx = 1:numel(functions)

    patient = functions{funcidx}(tomoplan, METRICS_LIST, patient);
    
end
    
end
